# Generated by cucumber-sinatra. (Fri Oct 22 17:42:33 -0200 2010)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'healthchecker.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Capybara.app = Sinatra

class SinatraWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  SinatraWorld.new
end
