---
projects:
  colaboracoes:
    id:     colaboracoes
    name:   Colaborações
    url:    http://colaboracoes.globo.com/healthcheck

  participacoes:
    id:     participacoes
    name:   Participações
    url:    http://participacoes.globo.com/healthcheck

  colaboracoes2:
    id:     colaboracoes2
    name:   Colaborações2
    url:    http://colaboracoes.globo.com/healthcheck

  participacoes2:
    id:     participacoes2
    name:   Participações2
    url:    http://participacoes.globo.com/healthcheck
