---
projects:
  colaboracoes:
    id:     colaboracoes
    name:   Colaborações
    url:    http://colaboracoes.globo.com/healthcheck
    imgOk:  /images/colaboracoes.jpg
    imgOut: /images/colaboracoes-red.jpg

  participacoes:
    id:     participacoes
    name:   Participações
    url:    http://participacoes.globo.com/healthcheck
    imgOk:  /images/participacoes.jpg
    imgOut: /images/participacoes-red.jpg