---
projects:
  globo:
    name:   Globo
    url:    http://www.globo.com/
  bing:
    name:   Bing
    url:    http://br.bing.com/
  xang:
    name:   Xang
    url:
      - http://xang.com/
      - http://xeng.com/
      - http://xing.com/